---
title: 'Permanova with Factor Control: GeoRegion'
output: html_document

knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, '06_03_annova_tests_factor_control_georegion.html'))})
---

#### Define Libraries
```{r echo=TRUE, message=FALSE, warning=FALSE, tidy=TRUE}
library("stringr")
library("dplyr")
library("vegan")
```

#### Define Path
```{r tidy=TRUE}
dir.wrk <- getwd()
dir.data <- file.path(dir.wrk, "data/data_household")
dir.annot <- file.path(dir.wrk, "data/data_annotations")
dir.process <- file.path(dir.wrk, "data/data_processed")
dir.output <- file.path(dir.wrk, "output")
```

#### Define Files
```{r tidy=TRUE}
file.dat <- file.path(dir.process, "household_level_data_frequency_table.tsv")
```

#### Define Categories
```{r}
type_eth <- c("Newar","Brahman","Madhesi","Chettri","Muslim−Others",
             "Gurung−Magar","Dalit","Rai−Limbu","Tamang","Chepang−Thami")
type_fuel <- c("Wood","Electricity","BioGas","Keroscene","LPGas","Others")
type_inc <- c("0-10000","10000-20000","20000-30000","30000-50000","50000-ABOVE")
type_edu <- c("Illiterate","NonFormal-Other","Primary","Secondary","University")
type_geo <- c("Himalayan","Hilly")

cpalette.eth <- c("#e31a1c","#a6cee3","#1f78b4","#b2df8a","#33a02c",
                  "#fb9a99","#fdbf6f","#ff7f00","#cab2d6","#6a3d9a")
cpalette.inc <- c("#fdd49e","#fdbb84","#fc8d59","#e34a33","#b30000")
cpalette.edu <- c("#bfd3e6","#9ebcda","#8c96c6","#8856a7","#810f7c")
cpalette.geo <- c("#35978f","#bf812d")
```

#### Load Frequency Table Data
```{r}
dat <- read.delim(file.dat, header=TRUE, stringsAsFactors=FALSE)
dat <- dat[-which(rowSums(dat[,5:10]) == 0),]

head(dat)
```

#### Transform Data to Log Scale
```{r}
dml <- vegan::decostand(dat[,5:10], "log")
dml <-  cbind(dat[,-c(5:10)], dml)
dml$Ethnicity <- factor(dml$Ethnicity, levels=type_eth)

head(dml)
```


#### Function: get_permanova()
```{r}
get_permanova <- function(dm, control_geo, type_eth, type_inc, type_edu){
     # Retain Data for Control GeoRegion ---
     dm <- subset(dm, dm$GeoRegion == control_geo)  
  
     # Factorize ---
     dm$Ethnicity <- factor(dm$Ethnicity, levels=type_eth)
     dm$IncomeGroup <- factor(dm$IncomeGroup, levels=type_inc)
     dm$EducationLevel <- factor(dm$EducationLevel, levels=type_edu)
  
     # Compute Distance Matrix ---
     dist_dm <- vegan::vegdist(x=as.matrix(dm[,5:10]), method="euclidean", binary=FALSE, diag=TRUE, upper=TRUE, na.rm = FALSE)

     # Adonis test ---
     set.seed(12345)
     y_permanova <- vegan::adonis(dist_dm ~ Ethnicity+IncomeGroup+EducationLevel, 
                                  data=dm, permutations=999, method="euclidean", parallel=4)

     return(y_permanova)
}
```


#### Get Permanova by Control GeoRegion
```{r}
list.permanova <- list()
for(i in 1:length(type_geo)){
  control_geo <- type_geo[i] 
  d <- get_permanova(dm=dml, control_geo, type_eth, type_inc, type_edu)
  list.permanova[[i]] <- cbind(Control_GeoRegion=control_geo,  Factor=rownames(as.data.frame(d$aov.tab)),  as.data.frame(d$aov.tab))
}

# Aggregate Results ---
df <- do.call(rbind.data.frame, list.permanova)
rownames(df) <- c(1:nrow(df))

head(df)

# Write Table ---
file.output <- file.path(dir.output, "stats_abundance_permanova_factorcontrol_georegion.tsv")
write.table(df, file.output, sep="\t", row.names=FALSE, col.names=TRUE, quote=FALSE)
```

