---
title: "Nudging households towards clean cooking: the role of group segmentation based on diversity in fuel choice"

author:
  - name: "**Ratna K. Shrestha**"
    affiliation: Vancouver School of Economics, University of British Columbia
  - name: "**Raunak Shrestha**"
    affiliation: Department of Urologic Sciences, University of British Columbia; Vancouver Prostate Centre

output: html_document

knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

### Abstract
> Despite significant direct subsidies as well as nonmonetary incentives, the rate of transition to clean cooking has fallen short of expectations; over 3 billion people worldwide, mostly from developing countries, still rely on solid fuels for cooking. Here, we draw upon the insights from behavioural economics and data analytics in developing better-targeted “nudges” towards clean cooking. Devising individually customized nudges would be theoretically ideal but prohibitively costly in practice. Therefore, segmenting households into more homogenous subgroups based on certain socio-economic or behavioural factors is an important first step. For this analysis, we use the post Gorkha-earthquake data from Nepal on 747,137 households’ fuel-choice pattern. We find that ethnicity explains the highest intergroup diversity (39.12%), followed by income (26.30%), education (12.62%), and location (4.05%). Once the factor with the highest discriminatory power is identified, we segregate the households into subgroups and offer several potential nudges that align with the fuel-choice pattern of each subgroup or cluster of subgroups. Such subgroup-based nudges may be less costly and yet outperform the traditional economic incentives in promoting clean cooking.

### Dataset
Following the 7.8 Mw Gorkha Earthquake in Nepal on April 25, 2015, the Kathmandu Living Labs in collaboration with the National Planning Commission (the Government of Nepal), carried out the largest household survey ever done in Nepal using mobile technology. Although the primary objective of this survey was to assess damages inflicted by the quake and identify beneficiaries eligible for government’s housing reconstruction grants, the data contain many other kinds of valuable socio-economic information, including the types of fuel used by households for cooking and lighting from 11 of the most earthquake-affected districts of Nepal, excluding the Kathmandu valley. 

The data for all 11 districts were downloaded from the **2015 Nepal Earthquake: Open Data Portal** (<http://eq2015.npc.gov.np/>). 
<br/><br/>

### Analysis

| S.No. | Analysis                                                                                                                                             |
|-------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1.00  | [Home](https://raunakms.github.io/diversity_cooking_fuel/){target="_blank"}                                                                          |
| 1.01  | [Data Pre-processing](https://raunakms.github.io/diversity_cooking_fuel/01_01_data_preprocess.html){target="_blank"}                                |
| 2.01  | [Data Preparation to Generate Choropleth Maps](https://raunakms.github.io/diversity_cooking_fuel/02_01_maps_data_preparation.html){target="_blank"} |
| 2.02  | [Generate Choropleth Maps](https://raunakms.github.io/diversity_cooking_fuel/02_02_maps_plot.html){target="_blank"}                                 |
| 3.01  | [Baseline Data](https://raunakms.github.io/diversity_cooking_fuel/03_01_baseline_data.html){target="_blank"}                                |
| 4.01  | [Ordination Analysis](https://raunakms.github.io/diversity_cooking_fuel/04_01_ordination_analysis.html){target="_blank"} |
| 5.01  | [Alpha Diversity](https://raunakms.github.io/diversity_cooking_fuel/05_01_alpha_diversity.html){target="_blank"}                                 |
| 6.01  | [Annova Tests](https://raunakms.github.io/diversity_cooking_fuel/06_01_annova_tests.html){target="_blank"}                                |
| 6.02  | [Annova Tests with Factor Control: IncomeGroup](https://raunakms.github.io/diversity_cooking_fuel/06_02_annova_tests_factor_control_income.html){target="_blank"} |
| 6.03  | [Annova Tests with Factor Control: GeoRegion](https://raunakms.github.io/diversity_cooking_fuel/06_03_annova_tests_factor_control_georegion.html){target="_blank"}                                 |

<br/><br/>

#### Code availability
R-codes used for data analysis is available at [https://raunakms.github.io/diversity_cooking_fuel](https://raunakms.github.io/diversity_cooking_fuel) and can be downloaded from [https://github.com/raunakms/diversity_cooking_fuel](https://github.com/raunakms/diversity_cooking_fuel)
<br/><br/>

#### Citation
Shrestha, Ratna K. and Shrestha, Raunak. **Nudging households towards clean cooking: the role of group segmentation based on diversity in fuel choice**. 2019. (*submitted*)<br/>
See details [here](http://raunakms.github.io/publication/2019_cooking_fuel/)
<br/><br/>

#### Corresponding author
Ratna K. Shrestha, PhD <br/>
Vancouver School of Economics, <br/>
University of British Columbia, <br/>
6000 Iona Drive, Vancouver, BC, Canada V6T 1L4 <br/>
E-mail: ratna.shrestha [at] ubc.ca<br/>

